"""
Django settings for Order1 project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-p72_z)5n1-c9mbpo4&9h1ab9ha=+wbf^351mz@oi@(gj383^sv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    # 'django.contrib.admin',
    # 'django.contrib.auth',
    # 'django.contrib.contenttypes',
    # 'django.contrib.sessions',
    # 'django.contrib.messages',
    'django.contrib.staticfiles',
    'web.apps.WebConfig',
    'web.templatetags.menu',
    'web.templatetags.buttons',
]

MIDDLEWARE = [
    # 'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'middlewares.login_sessions_check.LoginSessionsCheckMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    # 'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Order1.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                # 'django.contrib.auth.context_processors.auth',
                # 'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Order1.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# session
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'

SESSION_COOKIE_NAME = "sessionid"  # Session的cookie保存在浏览器上时的key，即：sessionid＝随机字符串
SESSION_COOKIE_PATH = "/"  # Session的cookie保存的路径
SESSION_COOKIE_DOMAIN = None  # Session的cookie保存的域名
SESSION_COOKIE_SECURE = False  # 是否Https传输cookie
SESSION_COOKIE_HTTPONLY = True  # 是否Session的cookie只支持http传输
SESSION_COOKIE_AGE = 1209600  # Session的cookie失效日期（2周）

SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # 是否关闭浏览器使得Session过期
SESSION_SAVE_EVERY_REQUEST = True  # 是否每次请求都保存Session，默认修改之后才保存

# 自定义配置
LOGIN_HOME = '/home/'
ORDER_WHITE_URL = ['/login/', '/sms_login/', '/sms_send/', 'http://127.0.0.1:8000/']
ORDER_LOGIN_URL = '/login/'
ORDER_USER_INFO = 'user_info'
ORDER_TASK_NAME = 'VIDEO_TASK'

ORDER_MENU = {
    'CUSTOMER': [
        {
            'title': '订单中心',
            'children': [
                {
                    'title': '订单管理',
                    'url': '/order/',
                    'name': 'order',
                },
            ]
        },
        {
            'title': '其他',
            'children': [
                {
                    'title': '交易记录',
                    'url': '/order/list/',
                    'name': 'order_list',
                },
            ]
        },
    ],

    'ADMIN': [
        {
            'title': '用户管理',
            'children': [
                {
                    'title': '级别管理',
                    'url': '/level/',
                    'name': 'level',
                },
                {
                    'title': '用户管理',
                    'url': '/customer/',
                    'name': 'customer',
                },
                {
                    'title': '价格策略',
                    'url': '/price/',
                    'name': 'price',
                },
            ]
        },
    ],

}

ORDER_PREMISSION_PUBLIC = {
    'login': {'title': '登录', 'parent': None},
    'sms_send': {'title': '发送短信', 'parent': None},
    'sms_login': {'title': '短信登陆', 'parent': None},
    'home': {'title': '首页', 'parent': None},
    'logout': {'title': '注销', 'parent': None}
}

ORDER_PREMISSION = {
    'CUSTOMER': {
        'order': {'title': '订单系统', 'parent': None},
        'order_add': {'title': '创建订单', 'parent': 'order'},
        'order_list': {'title': '交易记录', 'parent': 'order'},
        'order_cancel': {'title': '撤单', 'parent': 'order'},
    },
    'ADMIN': {
        'level': {'title': '级别管理', 'parent': None},
        'level_add': {'title': '级别添加', 'parent': 'level'},
        'level_edit': {'title': '级别编辑', 'parent': 'level'},
        'level_delete': {'title': '级别删除', 'parent': 'level'},

        'customer': {'title': '用户管理', 'parent': None},
        'customer_add': {'title': '用户创建', 'parent': 'customer'},
        'customer_edit': {'title': '用户编辑', 'parent': 'customer'},
        'customer_reset': {'title': '重置密码', 'parent': 'customer'},
        'customer_delete': {'title': '删除用户', 'parent': 'customer'},
        'customer_trade': {'title': '交易记录', 'parent': 'customer'},
        'customer_trade_add': {'title': '增加交易记录', 'parent': 'customer'},

        'price': {'title': '价格策略', 'parent': None},
        'policy_delete': {'title': '价格策略删除', 'parent': 'price'},
        'price_edit': {'title': '价格策略编辑', 'parent': 'price'},
        'price_add': {'title': '价格策略增加', 'parent': 'price'},

    },
}

try:
    from .local_settings import *
except Exception as e:
    print(e)
