# Generated by Django 3.2 on 2024-03-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(3, '完成'), (4, '失败'), (2, '正在执行'), (5, '无'), (1, '待执行')], default=5, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='transactionrecord',
            name='charge_type',
            field=models.IntegerField(choices=[(1, '充值'), (2, '扣款'), (3, '创建订单'), (4, '删除订单'), (5, '撤单')], verbose_name='交易类型'),
        ),
    ]
