# Generated by Django 3.2 on 2024-03-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20240308_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(3, '完成'), (2, '正在执行'), (1, '待执行'), (4, '失败'), (5, '无')], default=5, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='transactionrecord',
            name='charge_type',
            field=models.IntegerField(choices=[(2, '扣款'), (4, '删除订单'), (1, '充值'), (5, '撤单'), (3, '创建订单')], verbose_name='交易类型'),
        ),
    ]
