# Generated by Django 3.2 on 2024-03-08 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20240308_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='level',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.DeleteModel(
            name='PricePolicy',
        ),
        migrations.RemoveField(
            model_name='transactionrecord',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='transactionrecord',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Administrator',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Level',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='TransactionRecord',
        ),
    ]
