# Generated by Django 3.2 on 2024-03-22 11:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20240308_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(db_index=True, max_length=11, validators=[django.core.validators.RegexValidator('^1[3|4|5|7|8][0-9]{9}$', '手机格式错误')], verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='level',
            name='percent',
            field=models.IntegerField(help_text='输入0-100整数为折扣百分比', verbose_name='折扣'),
        ),
        migrations.AlterField(
            model_name='level',
            name='title',
            field=models.CharField(max_length=32, verbose_name='级别'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(4, '失败'), (2, '正在执行'), (3, '完成'), (5, '无'), (1, '待执行')], default=5, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='transactionrecord',
            name='charge_type',
            field=models.IntegerField(choices=[(2, '扣款'), (5, '撤单'), (3, '创建订单'), (4, '删除订单'), (1, '充值')], verbose_name='交易类型'),
        ),
        migrations.AlterField(
            model_name='transactionrecord',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.administrator', verbose_name='管理员'),
        ),
    ]
